$filter("translate")("format_from_date"),
  format_from_date: "From date don't match format",
    format_to_date: "To date don't match format",
      from_to_date: "To date must greater than from date",
        check_from_to: "End date must be greater than start date", 
            delete_item: "Please choose item to delete!",
              edit_item: "Please choose item to edit!",
                email_error: "Email invalidate",
                  date_from_to: "From date and to date invalid",
                    SUCCESS: "Success",
                      WARNING: "Warning",
                        Save_Error: "Save Error",
                          Save_Success: "Save Success",
                            Delete_Error: "Delete Error.",
                              Delete_Success: "Delete Success.",
                                Yes_delete_it: "Yes, delete it!",
                                  Are_you_sure: "Are you sure?",
                                    DELETED: "Deleted",
                                      UPLOAD_ITEM_SUCCESS: "Upload image success",
                                        UPLOAD_ITEM_ERROR: "Upload image error",