let dt_save_deposit = {
    // apartment_sales_deposit_id: 0,
    apartment_sales_contract_id: 0,
    room_id: $scope.room_id,
    receiver_name: $scope.deposit.receiver_id,
    owner_deposit_name: $scope.deposit.owner_deposit_name,
    owner_deposit_last_name: $scope.deposit.owner_deposit_last_name,
    owner_deposit_phone: $scope.owner_deposit_phone_temp,
    owner_deposit_email: $scope.deposit.owner_deposit_email,
    deposit_date: $scope.fromDateDepositTemp,
    currency_code: $scope.deposit.currency_code,
    deposit_amount: utility.so_tra_ve_binh_thuong($scope.deposit.deposit_amount),
    deposit_total: utility.so_tra_ve_binh_thuong($scope.deposit.deposit_total),
    exchange_rate: utility.so_tra_ve_binh_thuong($scope.deposit.exchange_rate),
    owner_currency: $scope.deposit.owner_currency,
    owner_deposit_amount: Math.round(utility.so_tra_ve_binh_thuong($scope.deposit.owner_deposit_amount)),
    owner_deposit_total: Math.round(utility.so_tra_ve_binh_thuong($scope.deposit.owner_deposit_total)),
    created_by_id: $scope.u_id,
    created_by_name: $scope.u_name,
    identity_type: 1,
    identity_number: utility.getString($scope.deposit.identity_number),
    identify_created: $scope.identifyCreatedDepositTemp,
    identify_expired: $scope.identifyExpiredDepositTemp,
    identify_place: utility.getString($scope.deposit.identify_place),
    deposit_date_to: $scope.toDateDepositTemp,
    content: $scope.deposit.content,
    request_status: 1,
    remark: $scope.deposit.remark,
    bank_id: utility.getString($scope.deposit.bank_id),
    bank_name: utility.getString($scope.deposit.bank_name),
    payment_type: utility.getString($scope.deposit.payment_type),
    address_contact: $scope.deposit.address_contact,
    apartment_sales_marketing_id: apartment_sales_marketing_id,
    owner_nationality_id: $scope.deposit.owner_nationality_id,
    owner_area_code: $scope.deposit.country,
    agent_id: $scope.deposit.agent_id,
    status: $scope.deposit.status,
    commission_type: $scope.deposit.commission_type,
    commission_value: utility.so_tra_ve_binh_thuong($scope.deposit.commission_value),
    commission_amount: utility.so_tra_ve_binh_thuong($scope.deposit.commission_amount),
    /* tong tien coc */
    total_amount: utility.so_tra_ve_binh_thuong($scope.deposit.total_price),
    discount_type: $scope.deposit.discount_type,
    /* phan tram chien khau */
    discount_value: utility.so_tra_ve_binh_thuong($scope.deposit.discount_value),
    /* tien chiet khau */
    discount_amount: utility.so_tra_ve_binh_thuong($scope.deposit.discount_amount),
    "total_amount_after_discount": utility.so_tra_ve_binh_thuong($scope.deposit.total_amount_after_discount),
    "price_per_m2": utility.so_tra_ve_binh_thuong($scope.objectDeposit.price_per_m2),
    "acreage": utility.so_tra_ve_binh_thuong($scope.objectDeposit.acreage),
    "construction_cost": utility.so_tra_ve_binh_thuong($scope.objectDeposit.construction_cost),
    "cost_of_land_use_rights": utility.so_tra_ve_binh_thuong($scope.objectDeposit.cost_of_land_use_rights),
    /* chuong trinh khuyen mai */
    "promotion_id": $scope.detail_contract.article3_promotion_id,
    /* gia tri khuyen mai */
    "promotion_amount": utility.so_tra_ve_binh_thuong($scope.detail_contract.article3_promotion_amount),
    /* tru cong no */
    "promotion_paid_debt": $scope.detail_contract.article3_promotion_paid_debt,
    "payment_method_id": $scope.deposit.payment_cycle_id,
    "approve_status": 0,
    "tax": 10,
    "vat": utility.so_tra_ve_binh_thuong($scope.deposit.vat),
    "grand_total": utility.so_tra_ve_binh_thuong($scope.roomsDetail.grandTotal1),
    "discount_paid_debt": $scope.deposit.tru_trong,
    "deposit_total_paid": utility.so_tra_ve_binh_thuong($scope.deposit.tien_coc_da_tra),
    "is_complete": 0,
}